train:
  device: cuda:0
  epoch: 3
  lr: 0.001
  name: DeepLerning
  optimizer: sgd
  wd: 0.0
  amp: true
data:
  batch_size_eval: 128
  batch_size_train: 128
  class_num: 10
  data_size: 28
  name: MNIST
model:
  in_chans: 1
  name: resnet50
  pre_train: true
