trainer:
  seed: 42
  epoch: 25
  device: cuda:0
  amp: true
  task: classification
  mix_up: true
  optimizer:
    name: adamW
    lr: 0.0004
    wd: 1.0e-06
    momentum: 0.9
    scheduler: cosine_warmup
    warmup_t_rate: 0.12
    warmup_lr_init_rate: 0.1
  dataset:
    name: Birdclef2024
    eval_rate: 0.2
    root_dir: /mnt/d/data/
    img_size: 256
    seed: 0
  model:
    name: ''
    backbone: eca_nfnet_l0
    pre_train: true
    in_chans: 3
    out_dim: 182
  dataloader:
    batch_size_train: 128
    batch_size_eval: 128
    num_workers: 8
logger:
  log_uri: /mnt/d/log/birdclef2024/mlruns
  experiment_name: 0000_test_expr
  run_name: test_run
