train:
  device: cuda:0
  epoch: 30
  lr: 0.0001
  name: DeepLerning
  optimizer: sgd
  wd: 0.0001
  amp: true
data:
  batch_size_eval: 64
  batch_size_train: 64
  class_num: 65
  data_size: 224
  name: OfficeHome
  # fold_n: 5
  # fold: 0
model:
  in_chans: 3
  name: resnet50
  pre_train: true
